from selenium import webdriver
from time import sleep 
driver = webdriver.Firefox(executable_path="./geckodriver")
driver.get('http://35.225.243.133/admin/')
sleep(2)
name=driver.find_element_by_css_selector('#id_username')
name.send_keys('student')
password=driver.find_element_by_css_selector('#id_password')
password.send_keys('qatester')
login=driver.find_element_by_css_selector('#login-form > div.submit-row > input[type=submit]')
login.click()
add_blog=driver.find_element_by_css_selector('#content-main > div > table > tbody > tr.model-blog > td:nth-child(2) > a')
add_blog.click()
sleep(0.5)
add_blog_title=driver.find_element_by_css_selector('#id_title')
add_blog_title.send_keys('bashlig')
sleep(0.5)
add_blog_descrp=driver.find_element_by_css_selector('#id_short_description')
add_blog_descrp.send_keys('ascknaslkcmadklncvadklnvadkl')
sleep(0.5)
add_blog_blg_name=driver.find_element_by_css_selector('#id_blogger_full_name')
add_blog_blg_name.send_keys('blogname')
sleep(0.5)
add_blog_content=driver.find_element_by_css_selector('#id_content')
add_blog_content.send_keys('blog content')
sleep(0.5)
save=driver.find_element_by_css_selector('#blog_form > div > div > input.default')
save.click()
sleep(2)
driver.get('http://35.225.243.133/admin/')
blogger_add=driver.find_element_by_css_selector('#content-main > div > table > tbody > tr.model-blogger > td:nth-child(2) > a')
blogger_add.click()
blogger_add_fullname=driver.find_element_by_css_selector('#id_full_name')
blogger_add_fullname.send_keys('amilalizda')
blogger_add_save=driver.find_element_by_css_selector('#blogger_form > div > div > input.default')
blogger_add_save.click()



sleep(2)
driver.close()